version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
  - master
  - v2.x
max_jobs: 1
image: Visual Studio 2017
clone_folder: c:\projects\azure-webjobs-sdk-templates
install:
- ps: >-
    .\getTools.ps1

    Install-Product node 10.15.2 x64
- cd .\Tools && npm install
build_script:
- ps: |
    Set-Location .\Functions.Templates
    $hasTag = Test-Path env:APPVEYOR_REPO_TAG_NAME
    if ($hasTag)
    {
      msbuild Functions.Templates.csproj /p:TemplateVersion=$env:APPVEYOR_REPO_TAG_NAME /target:PortalTemplatesPkg /target:VisualStudioTemplates  
    } else {
      msbuild Functions.Templates.csproj /p:TemplateVersion=$env:APPVEYOR_BUILD_VERSION /target:PortalTemplatesPkg /target:VisualStudioTemplates
    }
- dir && cd ..\Tools && .\node_modules\.bin\gulp.cmd build-all
- ps: |
    if ($hasTag)
    {
      Rename-Item -Path ..\Functions.Templates\bin\Portal\out.zip -NewName "$env:APPVEYOR_REPO_TAG_NAME.zip"
    } else {
      Rename-Item -Path ..\Functions.Templates\bin\Portal\out.zip -NewName "$env:APPVEYOR_BUILD_VERSION.zip"
    }
    ..\SignTools\RunSigningJob.ps1
artifacts:
  - path: Functions.Templates\bin\Portal\Nuget\*.nupkg
    name: Portal templates
  - path: Functions.Templates\bin\Portal\*.zip
    name: Portal templates
  - path: Functions.Templates\bin\ExtensionBundle-1.x\Nuget\*.nupkg
    name: ExtensionBundle templates v1.x
  - path: Functions.Templates\bin\ExtensionBundle-2.x\Nuget\*.nupkg
    name: ExtensionBundle templates v2.x
  - path: Functions.Templates\bin\VS\Release\*.nupkg
    name: Visual Studio templates
on_finish:
- ps: ..\SignTools\PollSigningResults.ps1